# Generated by Django 3.1.2 on 2020-10-04 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medium_scrap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='keyword',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medium_scrap.tag'),
        ),
    ]
