# Generated by Django 3.1.2 on 2020-10-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium_scrap', '0002_auto_20201004_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('author', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('responses', models.IntegerField()),
                ('claps', models.IntegerField()),
                ('tags', models.ManyToManyField(to='medium_scrap.Tag')),
            ],
        ),
    ]
