# Generated by Django 3.1.2 on 2020-10-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium_scrap', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sub_title',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
