# Generated by Django 3.1.2 on 2020-10-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium_scrap', '0005_auto_20201008_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='claps',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='responses',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
